POST http://localhost:3002/auth/login
content-type: application/json

{
    "username": "test",
    "password": "password"
}

###

POST http://localhost:3002/auth/signup
content-type: application/json

{
    "username": "test",
    "password": "password"
}

###

GET http://localhost:3002/auth/authenticated
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWZkYmQxYTMwYTNiMjk4MDg2NTk2NzEiLCJpYXQiOjE2NDQwMjA5MDd9.cIz7VcRv-Tj48dAMswd5kOn63P-L5Kwqwx9ULJZabrw

###

GET http://localhost:3002/workouts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWZkYmQxYTMwYTNiMjk4MDg2NTk2NzEiLCJpYXQiOjE2NDQwMjA5MDd9.cIz7VcRv-Tj48dAMswd5kOn63P-L5Kwqwx9ULJZabrw

###

POST http://localhost:3002/workouts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWZkYmQxYTMwYTNiMjk4MDg2NTk2NzEiLCJpYXQiOjE2NDQwMjA5MDd9.cIz7VcRv-Tj48dAMswd5kOn63P-L5Kwqwx9ULJZabrw

{
    "exerciseId": "62007db821bf6cdd9e795232",
    "exercise": "Abs",
    "activity": "Crunch",
    "reps": 10,
    "weight": 60
}

###

GET http://localhost:3002/exercises
content-type: application/json
